x-rails-environment:
  &rails_environment
  SECRET_KEY_BASE: ${SECRET_KEY_BASE}
  REDIS_URL: "redis://redis:6379/1"
  RAILS_ENV: production

x-rails_volumes:
  &rails_volumes
  - type: volume
    source: storage
    target: /opt/app/storage

x-rails-build:
  &rails_build
  context: .
  target: production
  args:
    REDIS_URL: "redis://redis:6379/1"

services:
  web:
    build:
      *rails_build
    volumes:
      *rails_volumes
    environment:
      << : *rails_environment
      RAILS_SERVE_STATIC_FILES: 1
  default_worker:
    build:
      *rails_build
    volumes:
      *rails_volumes
    environment:
      *rails_environment
  thumbnail_worker:
    build:
      *rails_build
    volumes:
      *rails_volumes
    environment:
      *rails_environment
  video_worker:
    build:
      *rails_build
    volumes:
      *rails_volumes
    environment:
      *rails_environment
volumes:
  storage:
