x-resque-environment:
  &resque_environment
  SECRET_KEY_BASE: ${SECRET_KEY_BASE}
  REDIS_URL: "redis://redis:6379/1"
  VERBOSE: 1

x-rails-build:
  &rails_build
  context: .
  args:
    REDIS_URL: "redis://redis:6379/1"

services:
  web:
    build:
      *rails_build
    image: ${COMPOSE_PROJECT_NAME}:latest
    ports: 
      - "127.0.0.1:${YTDLOR_WEB_PORT:-3000}:3000"
    depends_on:
      - db
      - redis
    environment:
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      REDIS_URL: "redis://redis:6379/1"
    command: rails server -b 0.0.0.0
  default_worker:
    build:
      *rails_build
    image: ${COMPOSE_PROJECT_NAME}:latest
    depends_on:
      - db
      - redis
    environment:
      << : *resque_environment
      QUEUE: default
    command: rake resque:work
  thumbnail_worker:
    build:
      *rails_build
    image: ${COMPOSE_PROJECT_NAME}:latest
    depends_on:
      - db
      - redis
    environment:
      << : *resque_environment
      QUEUE: thumbnail
    command: rake resque:work
  video_worker:
    build:
      *rails_build
    image: ${COMPOSE_PROJECT_NAME}:latest
    depends_on:
      - db
      - redis
    environment:
      << : *resque_environment
      QUEUE: video
    command: rake resque:work
  redis:
    image: redis
  db:
    image: postgres:14
    volumes:
      - type: volume
        source: postgres
        target: /var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
volumes:
  postgres:
