x-rails-build:
  &rails_build
  context: .
  target: production
  args:
    REDIS_URL: "redis://redis:6379/1"

x-rails_volumes:
  &rails_volumes
  - type: volume
    source: storage
    target: /opt/app/storage

services:
  auto_remove:
    build:
      *rails_build
    image: ${COMPOSE_PROJECT_NAME}:latest
    volumes:
      *rails_volumes
    depends_on:
      - db
      - redis
    init: true
    environment:
      RAILS_ENV: production
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      REDIS_URL: "redis://redis:6379/1"
      YTDLOR_AUTOREMOVE_INTERVAL: 15
      YTDLOR_AUTOREMOVE_FAILED_INTERVAL: 120
    command: ./autoremoved.sh
