services:
  auto_remove:
    build: .
    volumes:
      - type: volume
        source: db
        target: /var/opt/ytdlor/db
      - type: volume
        source: storage
        target: /var/opt/ytdlor/storage
    init: true
    environment:
      RAILS_ENV: production
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      REDIS_URL: "redis://redis:6379/1"
      YTDLOR_AUTOREMOVE_INTERVAL: 15
      YTDLOR_AUTOREMOVE_FAILED_INTERVAL: 120
    command: ./autoremoved.sh
