x-rails_volumes:
  &rails_volumes
  - type: bind
    source: .
    target: /opt/app

services:
  web:
    volumes:
      *rails_volumes
  default_worker:
    volumes:
      *rails_volumes
  thumbnail_worker:
    volumes:
      *rails_volumes
  video_worker:
    volumes:
      *rails_volumes
