default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues: "default"
      threads: 1
      processes: 1
      polling_interval: 1
    - queues: "thumbnail"
      threads: 1
      processes: 1
      polling_interval: 1
    - queues: "video"
      threads: 1
      processes: 1
      polling_interval: 1

development:
 <<: *default

test:
 <<: *default

production:
 <<: *default
