name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: PreCompile assets
        run: ./docker_compose --profile test run --rm --build test rails assets:precompile
      - name: Create database
        run: ./docker_compose --profile test run --rm --build test rails db:create
      - name: Run tests on docker compose
        run: ./docker_compose --profile test run --rm --build test rails test:system
      - name: Upload Logs
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: log
          path: log/test.log
